### ISSUE TITLE
React.PropTypes.shape is undefined

### ISSUE THREAD

**Issue by emilwidlund** [Osedea/react-native-opengraph-kit#14]
This package is not working anymore since the migration of PropTypes to it's own module in v16.0. It can be solved by installing prop-types as a separate module and replace the "React.PropTypes"-occurrences in OpenGraphAwareInput.js and OpenGraphDisplay.js.

https://reactjs.org/blog/2017/04/07/react-v15.5.0.html

https://reactjs.org/blog/2017/09/26/react-v16.0.html
> The deprecations introduced in 15.x have been removed from the core package. React.createClass is now available as create-react-class, React.PropTypes as prop-types, React.DOM as react-dom-factories, react-addons-test-utils as react-dom/test-utils, and shallow renderer as react-test-renderer/shallow. See 15.5.0 and 15.6.0 blog posts for instructions on migrating code and automated codemods.

I could submit a PR when I got some spare time.

**Comment by adrienthiery** [comment]
Hey @emilwidlund !

I finally found some time to take care of it, so it should be all good in `1.6.0` 😄
