### ISSUE TITLE
Add Automated Tests

### ISSUE THREAD

**Issue by adrienthiery** [Osedea/react-native-opengraph-kit#4]
URLs to test with : 
- A minified HTML URL (ex: https://blog.callstack.io/react-native-animations-revisited-part-i-783143d4884)
- A redirection (ex: http://www.osedea.com)
- Non latin character websites (ex: http://cn.timesofisrael.com/)
- Website that right now sorta block the request (?) (ex: https://hi-in.facebook.com/, https://tw.news.yahoo.com/%E3%80%90%E7%8D%A8%E5%AE%B6%E3%80%91%E5%A4%9A%E9%87%8D%E9%98%BB%E5%9A%87%E8%A7%A3%E6%94%BE%E8%BB%8D%E3%80%80%E4%B8%AD%E7%A7%91%E9%99%A2%E5%AF%A6%E6%B8%AC%E5%A4%A9%E5%BC%93%E3%80%81%E5%A4%A9%E5%8A%8D-013928232.html)
- Links with relative image url : (ex: www.centrelapinscretins.com)

**Comment by teyou** [comment]
Thanks for the great component!

it seems that version 1.3.3 still unable to extract the data from this url.
[Yahoo chinese news site](https://tw.news.yahoo.com/%E3%80%90%E7%8D%A8%E5%AE%B6%E3%80%91%E5%A4%9A%E9%87%8D%E9%98%BB%E5%9A%87%E8%A7%A3%E6%94%BE%E8%BB%8D%E3%80%80%E4%B8%AD%E7%A7%91%E9%99%A2%E5%AF%A6%E6%B8%AC%E5%A4%A9%E5%BC%93%E3%80%81%E5%A4%A9%E5%8A%8D-013928232.html)

**Comment by adrienthiery** [comment]
Hmmm, you're right... I have to say I didn't try with non latin characters.

Let me take a look at it.

**Comment by adrienthiery** [comment]
The parser doesn't get the page... It gets only :
```
<!-- fe143.global.media.bf1.yahoo.com uncompressed/chunked Tue Jan 10 21:03:15 UTC 2017 -->
<!-- ncache10.global.media.bf1.yahoo.com compressed/chunked Tue Jan 10 21:03:15 UTC 2017 -->
```

**Comment by teyou** [comment]
you were right, I need to add a fake user-agent in order to get it works. 
I think Yahoo blocks those request without proper user-agent 

once I added [user-agent (mock Google bot)](https://support.google.com/webmasters/answer/1061943?hl=en), it works!

**Comment by adrienthiery** [comment]
Hi @teyou ,

I used the user-agent of the Google bot and did a bunch of improvements in the latest version, be sure to check it out and give me some feedback, it's really appreciated :)

**Comment by teyou** [comment]
Hi @adrienthiery ,

These are all [TLD list](https://data.iana.org/TLD/tlds-alpha-by-domain.txt)
I don't think we should whitelist the TLD within the regex

can try to parse this url: https://today.line.me/tw/article/cfdbb39a455f09e0d3eb3a532c455855ec46b4e0651de8ae29e768fe9519b74b?openExternalBrowser=1

it will fail because .me is not in (?:mil|mobi|museum|m[acdghklmnopqrstuvwxyz])

**Comment by adrienthiery** [comment]
Hi @teyou ,

I simplified the regexp in 1.4.1 so it should work now.

Sorry for the delay and thanks again for the feedback !

Would you mind creating new issues for further feedback, though, please?

Thanks a lot :)
