### ISSUE TITLE
It would be nice if can include an Example file

### ISSUE THREAD

**Issue by teyou** [Osedea/react-native-opengraph-kit#5]
It would be nice if can include an Example file on how to use this component :)

**Comment by teyou** [comment]
tried to parse by calling OpenGraphParser.extractMeta("https://blog.callstack.io/react-native-animations-revisited-part-i-783143d4884");

It seems that the parser is buggy.

``
returned data 
{ url: 'https://blog.callstack.io/react-native-animations-revisited-part-i-783143d4884',
  title: 'text/html; charset=utf-8' }
``

**Comment by adrienthiery** [comment]
Hi Rudy!

Thanks for the feedback.

That's weird, I use it everyday in a project and I didn't have that problem. I am gonna check it out and keep you updated!

**Comment by adrienthiery** [comment]
Oh ! I see, that's because the HTML file is minified so it's caught all as one line.

Should be fixed in v1.3.3

That's why I need to add tests 😅

**Comment by teyou** [comment]
Thanks for your prompt response.
Looking forward on the fix :)
