### ISSUE TITLE
google detection fails..

### ISSUE THREAD

**Issue by reut-co** [Osedea/react-native-opengraph-kit#8]
why 'www.google.com' detection doesn't work?

**Comment by adrienthiery** [comment]
Hi @reut-co,

Thanks for your interest in our component.

It works for me on the example project (`example/` folder) (see image hereafter), what is your configuration ?

![screen shot 2017-04-25 at 9 45 03 am](https://cloud.githubusercontent.com/assets/2392118/25388529/1c9b53aa-299c-11e7-8aa4-26d0d3450c91.png)

The only issue with google is that it doesn't provide any opengraph or meta data for the homepage, so the result is empty.

**Comment by jtewright** [comment]
@adrienthiery Google do provide og meta data. view-source:https://www.google.com/

Google's servers are blocking your request because it looks suspicious. Medium.com does the same, through CloudFlare. I think this is what @reut-co is talking about.

**Comment by jtewright** [comment]
Update -- I tried changing the user-agent in the request function, and just unsetting it, and it got Medium working. Google still doesn't work though. FB link debugger gets Google's data, so there must be a way to do it.

I don't really know about user agents and reading up on the specs doesn't help too much -- you seem to have them set as if the request's coming from a Mozilla browser and it's a Google crawler. Is that common practice?

**Comment by adrienthiery** [comment]
Hi @jtewright ,

Indeed, google provides a bit of meta-data :
```
<meta content="/images/branding/googleg/1x/googleg_standard_color_128dp.png" itemprop="image">
<link href="/images/branding/product/ico/googleg_lodp.ico" rel="shortcut icon">
```

I'm wondering if it is new because I'm pretty sure I checked when the issue was opened... Maybe I messed up 😅 

For some websites that are full JS, we need to use the Google Crawler User-agent, otherwise we don't get any of the content of the page, but it is understandable that Google blocks it... 
I think Cloudfare is trying to block any kind of scrapping, but I do not have solutions for that.

Any idea ?

I think Medium articles were working, though. Could it be you have done a lot of requests in not a lot of time ?

**Comment by adrienthiery** [comment]
I'm gonna try to implement the Google Crawler User-agent as a fallback only, so if a first request doesn't give data, we'll try a second time with the Google Crawler agent. That way we should be able to still get full JS Sites that detect Google's User Agent and prerender only then.

**Comment by adrienthiery** [comment]
Hi @reut-co @jtewright ,

This should be fixed into 1.5.1 !

Thanks for poking me again on that. 😃 

![simulator screen shot jul 11 2017 10 32 11 pm](https://user-images.githubusercontent.com/2392118/28103102-da64bca4-6688-11e7-9538-f6c6044ec7a9.png)

(proandroiddev.com is actually a Medium post)

**Comment by jtewright** [comment]
@adrienthiery nice! I'll give it a try.

re. whether I was hitting Medium with too many request, no I highly doubt that! unfortunately ;)

**Comment by jtewright** [comment]
@adrienthiery works! Great job :) Thank you.

**Comment by adrienthiery** [comment]
Thanks for the Feedback !

**Comment by jtewright** [comment]
YouTube isn't liking it now. Just returns 'YouTube' as title attribute. Do you get the same?

**Comment by adrienthiery** [comment]
Hi @jtewright ,
Yup...

Google is not working anymore either 😕

**Comment by jtewright** [comment]
k thanks for confirming! I might try doing this server side

**Comment by adrienthiery** [comment]
@jtewright : Came up with a workaround by calling `https://www.youtube.com/oembed?url=${youtubeVideoURL}&format=json`.

And I added some tests for Google and Youtube.

Gonna publish that as 1.5.2

**Comment by jtewright** [comment]
Thanks Adrien, it works!

Do you anticipate it breaking again? Is it YT servers developing a distaste after a certain frequency or number of hits, or something??

**Comment by jtewright** [comment]
Ah I see. Perhaps it's part of their battle with Facebook. Thanks!
